### PR TITLE
added ulb to be loaded from filesystem

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/3)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Door43DataFetcher.js, line 34 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/3#-KVk8XZ6KgOzyBTYq7Bk:-KVk8XZ6KgOzyBTYq7Bl:blgh48c) ([raw file](https://github.com/translationcoreapps/translationnotes_check_plugin/blob/256ae1bc1a0c7988f7e73203f242301173ad88b7/Door43DataFetcher.js#L34)):*
> ```JavaScript
> 			for (let v of ch.verses) {
> 				let regRes;
> 				try {
> ```

tabs lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/3)*

**Comment by mannycolon** [comment]
@RoyalSix this PR looks good to me  just removed the tabs

**Comment by RoyalSix** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Door43DataFetcher.js, line 34 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/3#-KVk8XZ6KgOzyBTYq7Bk:-KVpnRSSSdRAlojYU0kz:b-896fix) ([raw file](https://github.com/translationcoreapps/translationnotes_check_plugin/blob/256ae1bc1a0c7988f7e73203f242301173ad88b7/Door43DataFetcher.js#L34)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary>
> tabs lol
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/3)*

**Comment by ihoegen** [comment]
@RoyalSix  See my comment on https://github.com/translationCoreApps/translationWords_Check_plugin/pull/2

**Pull request merged**
