### PR TITLE
Added ability to show or hidde thelps

### PR DESCRIPTION
**Pull request by EllDoubleYew**
#### This pull request addresses:

Addresses #762 in the main repo

#### How to test this pull request:

Click the arrow that now hangs off the left side of the thelps section. This should open and close it like a drawer.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/33)

### CODE REVIEW

**Comment by ihoegen** [comment]
image


Something is wonky here

**Comment by ihoegen** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/33)*

**Comment by ihoegen** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/33)*

**Comment by mannycolon** [comment]
@ihoegen same here. just merged master into this branch which should handle some of your issues. however, not the disappearing chevron bug.

**Comment by EllDoubleYew** [comment]
@ihoegen 😵 thats super weird, I guess I didnt come across any tHelps info that long. What could cause that?

**Comment by ihoegen** [comment]
Probably need to switch from a height of 100% to a fixed height and an
overflow

**Pull request merged**
