### PR TITLE
modified the progress action for tN

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/55)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[FetchData/TranslationNotes.js, line 34 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/55#-KihoqJhxm8KceSFSUfa:-KihoqJiK8hqb8GO3H-6:badovux) ([raw file](https://github.com/translationcoreapps/translationnotes_check_plugin/blob/6b57621bba98f173c24059da4e46ee9f9a9ceef3/FetchData/TranslationNotes.js#L34)):*
> ```JavaScript
>     var DoorDataFetcher = new Door43DataFetcher();
>     var chapterData = {};
>     //progress("translationNotes", done / total * 100);
> ```

This is commented out, do we still need it here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/55)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/55)*

**Comment by klappy** [comment]
*[FetchData/ScripturePane.js, line 63 at r2](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/55#-Kiqz-6ZNmVB_faSR9lK:-Kiqz-6_XuO7qIt3xgmb:b-9gkd8a) ([raw file](https://github.com/translationcoreapps/translationnotes_check_plugin/blob/038965cf93d8319b29ad0786b247feb8c3360503/FetchData/ScripturePane.js#L63)):*
> ```JavaScript
>     }).then(() => {
>       progress("scripturePane", 100);
>       resolve();
> ```

I think resolve is being called before 100 can be rendered on screen. Not an issue just something to keep in mind on why it doesn't show.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/55)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/55)*

**Pull request merged**
