### PR TITLE
Make filters more specific

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This fixes an apparent issue in translationNotes, where filters aren't always matching. 

#### How to test this pull request:

Open both an Ephesians project and Titus project, and use this spreadsheet to make sure that the data is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/57)

### CODE REVIEW

**Comment by mannycolon** [comment]
@ihoegen Hey everything looks good. Just remove the console log.

What specific bugs does it address. Like can you give an example so I can track it down and test it is being fized with this PR.

**Comment by ihoegen** [comment]
@mannycolon It addresses #857 QA Fails. Some of the missing checks are missing because of a change in the data source, so we will have to have the content team discuss that portion, but I brought back what I could.

**Comment by mannycolon** [comment]
@ihoegen thanks for explaining it to me. great job. looks good to go just fix merge conflicts.

**Comment by mannycolon** [comment]
@ihoegen waiting on merge conflicts fix.

**Comment by mannycolon** [comment]
@ihoegen waiting on merge conflicts fix.

**Comment by ihoegen** [comment]
@mannycolon Just fixed them

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/57#-:-KjKr_eghe9P8OBkPKe8:bnfp4nl)*

**Pull request merged**
