### PR TITLE
updated colors, removed old files

### PR DESCRIPTION
**Pull request by cdwhitfield73**
#### This pull request addresses:

updated colors in css, removed some very old subcomponent files that are no longer used

#### How to test this pull request:

open tNotes and make sure I didn't break it!

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/67)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/67)*

**Comment by mannycolon** [comment]
@klappy didn't we say we would not delete files?

**Comment by klappy** [comment]
@mannycolon We talked about making sure who ever deleted was somebody well familiar with the code base. I thought Ian mentioned overseeing file removal and you agreed.

**Comment by mannycolon** [comment]
@klappy it's ok but I remember Ben saying we would hold back on that for later.

**Comment by ihoegen** [comment]
@mannycolon @klappy I approved the file deletions, as it was quick, and somewhat relevant to the issue

**Pull request merged**
