### PR TITLE
Refactored Translation Notes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Refactored translationNotes to the new data structure.

#### How to test this pull request:
To test this PR try opening tN on various projects

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/46)

### CODE REVIEW

**Comment by ihoegen** [comment]
Don't merge yet, I think I still have a quick thing to do

**Comment by ihoegen** [comment]
Okay this is ready for review and merge now

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r1, 7 of 10 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/46)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/46#-:-Ki-o43pYsSOJgoHODgm:bnfp4nl)*

**Pull request merged**
