### PR TITLE
fetchdata redux

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/44)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[FetchData.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44#-KfjC8aU8bAH6OIrbLUV:-KfjC8aVzgHx2BWhYQnf:b-nuuma5) ([raw file](https://github.com/translationcoreapps/translationnotes_check_plugin/blob/f90ce82e353eea3414faaa0290c03499f0533853/FetchData.js#L12)):*
> ```JavaScript
>   * @param {Object} params - .
>   * @param {} progress -
>   * @param {callback} callback -
> ```

I don't think callback is a type, maybe Function? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44)*

**Comment by EllDoubleYew** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44)*

**Comment by mannycolon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[FetchData.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44#-KfjC8aU8bAH6OIrbLUV:-Kfly852FJjbiPik2D16:b-896fix) ([raw file](https://github.com/translationcoreapps/translationnotes_check_plugin/blob/f90ce82e353eea3414faaa0290c03499f0533853/FetchData.js#L12)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't think callback is a type, maybe Function? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44)*

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/44)*

**Pull request merged**
