### PR TITLE
Backtrack sources of Ephesiasn

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request addresses #857 by using an older version of Ephesians. 

#### How to test this pull request:

Take a look at the spreadsheet on #857, and make sure Epehsians and Titus have the appropriate amount of checks.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationnotes_check_plugin/64)

### CODE REVIEW

**Comment by klappy** [comment]
I'm wondering why the .csv had to change? wasn't that suppose to be a direct version of what they gave us?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/64#-:-KkQmfwLhQkJWu298EXu:b-dpo1z2)*

**Comment by klappy** [comment]
Reviewed 68 of 69 files at r1.
Review status: 68 of 69 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationnotes_check_plugin/64)*

**Comment by ihoegen** [comment]
@klappy It had to be changed because I had changed it in the past to try and get it to match the newer sources.

**Comment by klappy** [comment]
@ihoegen: Thanks, just wanted to confirm.

**Comment by klappy** [comment]
@ihoegen: This fixed 2/3 categories to match in number. Can you double check Metaphors? Somehow we grew to 23 metaphors! :o

**Pull request merged**
